### ISSUE TITLE
Incompatible ODS generation (float cell)

### ISSUE THREAD

**Issue by krzykos** [westonganger/rodf#36]
The library generates following XML for float cells:
```
<table:table-cell office:value-type="float" office:value="1">
</table:table-cell>
```

On the other hand, LibreOffice does the following:
```
<table:table-cell office:value-type="float" office:value="11010" calcext:value-type="float">
<text:p>11010</text:p>
</table:table-cell>
```

As a consequence, some libraries (like https://github.com/roo-rb/roo) fail to load such incompatible ODS.

Please add the `p` element inside the `table-cell` element.
The content might be copied from the `value` attribute.

I haven't checked whether the extra content is required by the ODS specification, but it will definitely improve the compatibility.

Version: `1.1.0`

**Comment by westonganger** [comment]
Some documentation regarding this issue:

- https://stackoverflow.com/questions/37398762/what-types-of-officevalue-type-and-calcextvalue-type-attributes-exist-in-l
- https://relatorio.tryton.org/bug23
- https://bugs.documentfoundation.org/show_bug.cgi?id=114919

Seems to be related to proposed OpenDocument 1.3 spec
- https://www.oasis-open.org/news/announcements/invitation-to-comment-on-open-document-format-for-office-applications-opendocumen

**Comment by westonganger** [comment]
Hmm I just read now that this regarding the inner tag, not `calcext` I will dig into this.

**Comment by westonganger** [comment]
@krzykos can you please verify if this required change applies to any other cell types?

**Comment by krzykos** [comment]
@westonganger the problem affects only `float` cells.

**Comment by westonganger** [comment]
@krzykos I have now updated master with the requested changes in d29e6f3. Please test and let me know how it works out.

**Comment by krzykos** [comment]
@westonganger The solution in `d29e6f3` works like a charm! :-) Thank you!

I would also be pleased if you released the working version to rubygems.

**Comment by westonganger** [comment]
v1.1.1 is now released which contains these changes.
