### ISSUE TITLE
Allow passing arbitrary attributes to `table()`

### ISSUE THREAD

**Issue by dmolesUC** [westonganger/rodf#40]
Currently `table()` seems to take a title (which becomes the `table:name` attribute) and nothing else. It would be convenient to be able to pass other attributes (e.g. `table:protected`) -- ideally without them all having to be hard-coded in advance.

My current workaround is to subclass `RODF::Table`, override the `xml` method completely, and use the procedural style instead of declarative --

```ruby
ss = RODF::Spreadsheet.new { … }
table = MyTableSubclass.new(
  'title', 
  additional_attributes: { 'table:protected' => 'true', …}
)
ss.tables << ss_table
```

-- but this is clunky.

**Comment by westonganger** [comment]
Ok I have now added the ability to specify a `:attributes` option on Table, Row, Column, & Cell. Please advise if the API for this is desirable. See the README for more details: https://github.com/westonganger/rodf#adding-arbitrary-xml-attributes

I see that you have some pretty in depth knowledge of the spec. It would be great if you could help us out by completing the Style List to the best of your ability and creating a similar XML Attributes List.

**Comment by dmolesUC** [comment]
I don't really know the spec all that well, just looking at the docs and cross-referencing against what I see when I save a spreadsheet. TBH I'm still figuring out what I need to do to create a table where exactly the cells I want are protected and nothing else is (e.g. blank rows/columns Calc seems to automatically add on opening).

**Comment by westonganger** [comment]
Ok no problem. That's how I do it too. Just please share any undocumented findings so that this painful back-and-forth work does not have to be repeated by others :)

**Comment by westonganger** [comment]
v1.2.0 is now released which contains these improvements.
