### ISSUE TITLE
Using Text Styles and/or Verbatim XML

### ISSUE THREAD

**Issue by RPGHacker** [westonganger/rodf#43]
I've been using rodf for quite a while now. I often need to work with .ods files, and I find it to be a pretty great and handy gem for that. However, today I'm struggling quite a bit trying to make a specific thing work with it, and I'm wondering whether it's possible at all.

So I'm currently in the process of writing a Ruby script that reads in two different .ods files containing localized texts, then compares these texts and writes out another .ods file, containing columns "old text", "new text" and "difference". The "difference" column is supposed to receive a diff of the two texts, created with Ruby gem "differ". The idea here is that I can quickly compare two revisions of localized texts with one another and find out what exactly changed between them.

For this, I want to utilize text styles. Removed words should be displayed in red, bold, strikethrough text; added words should be displayed in green, bold text. Everything else should be normal text. However, after half a day of trial and error, I couldn't figure out how to make this work.

At first I checked the documentation for rodf to see if there's any mention of text styles at all, but that doesn't seem to be the case. Next I tried just writing out HTML containing the text styles, like so:

`row.cell "<text:span text:style-name=\"added-text\">#{added_text}</text:span>"`

However, this doesn't work, presumeably because rodf uses Builder::XmlMarkup under the hood, which I assume implicitly escapes any text it receives. Therefore in the output .ods file, all I get is a verbatim `<text:span>` attribute, which of course isn't what I need.

Next I tried looking through the rodf source files to see if I could find a workaround, but so far I wasn't very successful.

Is there any way to do this at all right now?

**Comment by westonganger** [comment]
@RPGHacker any chance to take a look at a PR for this?

**Comment by RPGHacker** [comment]
I might, but probably not soon-ish. The script I used this in was something I only needed once so far, so I didn't have much of a reason to go back to it and clean it up yet. Plus, my knowledge about Ruby is actually still fairly limited at this point, so I'd first have to gain the confidence to mess with code that a bunch of people might use.

I do think it's just [a single function](https://github.com/westonganger/rodf/blob/215274337ae767908d6bb14fd08b7cc3c483a7d4/lib/rodf/span.rb#L13) that would need to be changed, though. (Well, that, and adding an example to the documentation). I don't reckon it would be too hard to implement, but I haven't quite learned how optional arguments in Ruby are parsed yet.

**Comment by westonganger** [comment]
Ok so I have implemented your suggestions in f49f335

It would be cool if you could give the changes a test on your project to verify that the behaviour is as you expected.

**Comment by RPGHacker** [comment]
Thanks, I'll give that a try later today!
Is there a way to test the current changes using gems? Or do I have to download manually?

**Comment by westonganger** [comment]
```
# Gemfile

gem "rodf", git: "https://github.com/westonganger/rodf", branch: "master"
```

**Comment by RPGHacker** [comment]
Ah, sorry, I'm not very familiar with gem files yet, I've only ever used gem from the command line (I pretty much only know the basics of Ruby, since I've only ever used it to write some quick helper scripts).

Is there a way to do the same thing using gem from the command line?
Alternatively, do you know of a very simple gem file tutorial that focuses on the basics so that I can figure out how to do it quickly?

**Comment by westonganger** [comment]
v1.2.0 is now released which contains these changes.

**Comment by RPGHacker** [comment]
I've just updated to 1.2.0 and can confirm that it works as desried with my script. After refactoring it like this:

```
style 'changed-text', family: :text do
	property :text, 'color' => '#FFC90E'
	property :text, 'font-weight' => 'bold'
end	

style 'added-text', family: :text do
	property :text, 'color' => '#579D1C'
	property :text, 'font-weight' => 'bold'
end		

style 'removed-text', family: :text do
	property :text, 'color' => '#C9211E'
	property :text, 'font-weight' => 'bold'
	property :text, 'text-line-through-type' => 'single'
end


# [...]

row.cell style: 'dialog-cell' do |cell|
	cell.paragraph do |paragraph|
		parts.each do |part|
			if part.start_with?('{change}')
				part.slice! '{change}'
				paragraph.span part, style: 'changed-text'
			elsif part.start_with?('{add}')
				part.slice! '{add}'
				paragraph.span part, style: 'added-text'
			elsif part.start_with?('{remove}')
				part.slice! '{remove}'
				paragraph.span part, style: 'removed-text'
			elsif part.start_with?('{original}')
				part.slice! '{original}'
				paragraph.span part
			else
				raise "Error parsing diff string output: \"#{diff_text}\""
			end
		end
	end
end
```

I still get the desired colored output text. Thanks for implementing my suggestion!
